FavoriteRestaurants/Models/Restaurant.cs
using System.Collections.Generic;

namespace FavoriteRestaurants.Models
{
  public class Restaurant
  {

    public Restaurant()
    {
      this.Reviews = new HashSet<Review>();
    }
    public int RestaurantId { get; set; }
    public string Name {get; set;}
    public string Description { get; set; }
    // public Dictionary <int, string> PriceLevel {get; set;}
    public string PriceLevel { get; set; }
    public string Rating { get; set; }
    public string Type {get; set;}

    public bool Vegetarian { get; set; }
    public int CuisineId { get; set; }
    public virtual Cuisine Cuisine { get; set; }
    public virtual ICollection<Review> Reviews { get; set; }
    
  }
  public enum PriceLevel
  {
    Cheap,
    Moderate,
    Expensive
  }

  public enum Rating
  {
    Bad,
    NotBad,
    Average,
    Good,
    Perfect
  }  
}

FavoriteRestaurants/Models/Restaurants.cs
namespace FavoriteRestaurants.Models
{
  public class Restaurant
  {
    public int RestaurantId { get; set; }
    public string Name {get; set;}
    public string Description { get; set; }
    public int PriceLevel {get; set;}
    public int Rating { get; set; }
    public string Type {get; set;}
    public bool Vegetarian { get; set; }
    public int CuisineId { get; set; }
    public virtual Cuisine Cuisine { get; set; }
  }

  public enum PriceLevel
  {
    Cheap = 1,
    Moderate = 2,
    Expensive = 3
  }

  public enum Rating
  {
    Bad = 1,
    NotBad = 2,
    Average = 3,
    Good = 4,
    Perfect = 5
  }  
}

FavoriteRestaurants/Controllers/CuisinesController.cs
using Microsoft.AspNetCore.Mvc;
using FavoriteRestaurants.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace FavoriteRestaurants.Controllers
{
  public class CuisinesController : Controller
  {
    private readonly FavoriteRestaurantsContext _db;

    public CuisinesController(FavoriteRestaurantsContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Cuisine> model = _db.Cuisines.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Cuisine cuisine)
    {
      _db.Cuisines.Add(cuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      thisCuisine.Restaurants = _db.Restaurants.Where(x => x.CuisineId == id).ToList();
      _db.SaveChanges();
      return View(thisCuisine);
    }

    public ActionResult Edit(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    [HttpPost]
    public ActionResult Edit(Cuisine cuisine)
    {
      _db.Entry(cuisine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      _db.Cuisines.Remove(thisCuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

FavoriteRestaurants/Controllers/RestaurantsController.cs
using Microsoft.AspNetCore.Mvc;
using FavoriteRestaurants.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FavoriteRestaurants.Controllers
{
  public class RestaurantsController : Controller
  {
    private readonly FavoriteRestaurantsContext _db;

    public RestaurantsController(FavoriteRestaurantsContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Restaurant> model = _db.Restaurants.Include(restaurants => restaurants.Cuisine).ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Type");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Restaurant restaurant)
    {
      _db.Restaurants.Add(restaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      return View(thisRestaurant);
    }

    public ActionResult Edit(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Type");
      return View(thisRestaurant);
    }

    [HttpPost]
    public ActionResult Edit(Restaurant restaurant)
    {
      _db.Entry(restaurant).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      return View(thisRestaurant);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      _db.Restaurants.Remove(thisRestaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    
    public ActionResult Search()
    {
      List<Restaurant> model = _db.Restaurants.Include(restaurants => restaurants.Cuisine).OrderBy(x => x.Type).ToList();
      List<string> modelTypes = new List<string>{};
      foreach (Restaurant restaurant in model)
      {
        modelTypes.Add(restaurant.Type);
      }
      List<string> removedDuplicates = modelTypes.Distinct().ToList();
      ViewBag.RestaurantType = removedDuplicates;
      return View();
    }

    [HttpPost]
    public ActionResult SearchResults(Restaurant searchRestaurant)
    { 
          
      List<Restaurant> allModels = _db.Restaurants.Include(restaurants => restaurants.Cuisine).ToList(); 
      List<Restaurant> foundModels = allModels.ToList();

      if (searchRestaurant.Name != null)
      {
        string nameSearch = searchRestaurant.Name.ToLower();
        foundModels = foundModels.FindAll(x => x.Name.ToLower().Contains(nameSearch) == true);
      }
      if (searchRestaurant.PriceLevel != null)
      {
        foundModels = foundModels.FindAll(x => x.PriceLevel.Contains(searchRestaurant.PriceLevel) == true);
      }
      if (searchRestaurant.Rating != null)
      {
        foundModels = foundModels.FindAll(x => x.Rating.Contains(searchRestaurant.Rating) == true);
      }
      if (searchRestaurant.Type != null)
      {
        foundModels = foundModels.FindAll(x => x.Type.Contains(searchRestaurant.Type) == true);
      }
      if (searchRestaurant.Vegetarian == true)
      {
        foundModels = foundModels.FindAll(x => x.Vegetarian == true);
      }
      return View(foundModels);
    }
  }
}

FavoriteRestaurants/Controllers/ReviewsController.cs
using Microsoft.AspNetCore.Mvc;
using FavoriteRestaurants.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FavoriteRestaurants.Controllers
{
  public class ReviewsController : Controller
  {
    private readonly FavoriteRestaurantsContext _db;

    public ReviewsController(FavoriteRestaurantsContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Review> model = _db.Reviews.Include(reviews => reviews.Restaurant).ToList();
      foreach(Review review in model)
      {
        Console.WriteLine(review.ReviewerName);
      }
      return View(model);
    }

    public ActionResult Create(int id)
    {
      // var thisReview = _db.Reviews.FirstOrDefault(reviews => reviews.RestaurantId == id);
      ViewBag.RestaurantId = id;
      Console.WriteLine(id);
      return View();
    }

    [HttpPost]
    public ActionResult Create(Review review)
    {
      _db.Reviews.Add(review);
      _db.SaveChanges();
      return RedirectToAction("Details", "Restaurants", new { id = review.RestaurantId} );
    }

    // To-Do: Add reviews to restaurant details

  }
}

FavoriteRestaurants/Views/Restaurants/Create.cshtml
@{
  Layout = "_Layout";
  ViewBag.Title = "Add Restaurant";
}

@using FavoriteRestaurants.Models
@model FavoriteRestaurants.Models.Restaurant

<div class="jumbotron">
  <h4>Add a new restaurant</h4>
</div>

<div class="form">
  @using (Html.BeginForm())
  {
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)
    <br>
    <br>
    @Html.LabelFor(model => model.Description)
    @Html.TextAreaFor(model => model.Description)
    <br>
    <br>
    @Html.LabelFor(model => model.PriceLevel, "Price Level")
    @Html.DropDownListFor(model => model.PriceLevel, new SelectList(Enum.GetValues(typeof(PriceLevel))), "Select Price Level")
    <br>
    <br> 
    @Html.LabelFor(model => model.Rating)
    @Html.DropDownListFor(model => model.Rating, new SelectList(Enum.GetValues(typeof(Rating))), "Select Rating")
    <br>
    <br> 
    @Html.LabelFor(model => model.Type)
    @Html.TextBoxFor(model => model.Type)
    <br>
    <br> 
    @Html.LabelFor(model => model.Vegetarian, "Vegetarian")
    @Html.RadioButtonFor(model => model.Vegetarian, true)
    <br>
    @Html.LabelFor(model => model.Vegetarian, "Non-Vegetarian")
    @Html.RadioButtonFor(model => model.Vegetarian, false)
    <br>
    <br>  
    @Html.LabelFor(model => model.Cuisine)
    @Html.DropDownList("CuisineId")
    <br>
    <br> 
    <input type="submit" value="Add new restaurant" class="btn btn-secondary" />
  }
</div>

<div class="link">@Html.ActionLink("Show all restaurants", "Index")</div>
@Html.Partial("Footer")

FavoriteRestaurants/Views/Restaurants/Delete.cshtml
@{
  Layout = "_Layout";
  ViewBag.Title = "Delete Restaurant";
}

@model FavoriteRestaurants.Models.Restaurant

<h2>Are you sure you want to delete information about this restaurant?</h2>

@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" class="btn btn-secondary"/>
}
@Html.ActionLink("Back to List", "Index")
@Html.Partial("Footer")

FavoriteRestaurants/Views/Restaurants/Details.cshtml
@{
  Layout = "_Layout";
  ViewBag.Title = "Details Restaurant";
}

@model FavoriteRestaurants.Models.Restaurant

<div class="jumbotron">
  <h2>@Html.DisplayFor(model => model.Name) Restaurant Details</h2>
</div>

<img src="https://www.gaiahotelspa.com/resourcefiles/mainimages/woodsidegrill-interior-2.jpg" class="img-fluid" alt="">

<hr />
<h3>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)</h3>
<h3>@Html.DisplayNameFor(model => model.PriceLevel): @Html.DisplayFor(model => model.PriceLevel)</h3>
<h3>@Html.DisplayNameFor(model => model.Rating): @Html.DisplayFor(model => model.Rating)</h3>
<h3>Restaurant Type: @Html.DisplayFor(model => model.Type)</h3>

@if(Model.Vegetarian == true)
{
  <h3>@Html.DisplayNameFor(model => model.Vegetarian): Yes</h3>
}
else
{
  <h3>@Html.DisplayNameFor(model => model.Vegetarian): No</h3>
}

<div class="links4">
  <div class="link">@Html.ActionLink("Back to list", "Index")</div>
  <div class="link">@Html.ActionLink("Edit Restaurant", "Edit", new { id = Model.RestaurantId })</div>
  <div class="link">@Html.ActionLink("Delete Restaurant", "Delete", new { id = Model.RestaurantId })</div>
  <div class="link">@Html.ActionLink("Write a Review", "Create", "Reviews",  new { id = Model.RestaurantId })</div>
</div>



@Html.Partial("Footer")

FavoriteRestaurants/Views/Restaurants/Edit.cshtml
@{
  Layout = "_Layout";
  ViewBag.Title = "Edit Restaurant";
}

@using FavoriteRestaurants.Models;
@model FavoriteRestaurants.Models.Restaurant

<h2>Edit Restaurant</h2>

<h4>Edit restaurant information for @Html.DisplayFor(model => model.Name):</h4>

<div class="form">
  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.RestaurantId)

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)
    <br>
    <br>
    @Html.LabelFor(model => model.Description)
    @Html.EditorFor(model => model.Description)
    <br>
    <br>
    @Html.LabelFor(model => model.PriceLevel, "Price Level")
    @Html.DropDownListFor(model => model.PriceLevel, new SelectList(Enum.GetValues(typeof(PriceLevel))), "Select Price Level")
    <br>
    <br>
    @Html.LabelFor(model => model.Rating)
    @Html.DropDownListFor(model => model.Rating, new SelectList(Enum.GetValues(typeof(Rating))), "Select Rating")
    <br>
    <br>
    @Html.LabelFor(model => model.Type)
    @Html.EditorFor(model => model.Type)
    <br>
    <br>
    @Html.LabelFor(model => model.Vegetarian)
    @Html.EditorFor(model => model.Vegetarian)
    <br>
    <br>
    @Html.LabelFor(model => model.Cuisine)
    @Html.DropDownList("CuisineId")
    <br>
    <br>
    <input type="submit" value="Save" class="btn btn-secondary"/>
  }
</div>

<p>@Html.ActionLink("Back to list", "Index")</p>
@Html.Partial("Footer")

FavoriteRestaurants/Views/Restaurants/Index.cshtml
@{
  Layout = "_Layout";
  ViewBag.Title = "All Restaurants";
}

@using FavoriteRestaurants.Models;
@model List<FavoriteRestaurants.Models.Restaurant>;

<div class="jumbotron">
  <h1>Restaurants</h1>
</div>
<img src="https://embed.widencdn.net/img/visitorlando/agaw2vzklc/1920x747px/orlando-magical-dining-month.jpeg?keep=c&q=70&crop=yes&u=gqonyf&use=z4hwl" class="img-fluid" alt="">

<div class="content">
  @if (@Model.Count == 0)
{
  <h3>No restaurants have been added yet!</h3>
} 

@foreach (Restaurant restaurant in Model)
{
  <li>@Html.ActionLink($"{restaurant.Name}", "Details", new { id = restaurant.RestaurantId }) | @restaurant.Cuisine.Type</li>
}
</div>


<div class="links2">
  <div class="link">@Html.ActionLink("Add new Restaurant", "Create")</div>
  <div class="link">@Html.ActionLink("See all cuisines", "Index", "Cuisines")</div>
</div>

@Html.Partial("Footer")

FavoriteRestaurants/Views/Restaurants/Search.cshtml
@{
  Layout = "_Layout";
  ViewBag.Title = "Search Restaurants";
}

@using FavoriteRestaurants.Models
@model FavoriteRestaurants.Models.Restaurant

<div class="jumbotron">
  <h2>Search Restaurants</h2>
</div>

<div class="form">
  @using (Html.BeginForm("SearchResults", "Restaurants", FormMethod.Post))
  {
    @Html.Label("Enter your desired search criteria below")
    <hr>
    @Html.Label("By Name")
    @Html.TextBoxFor(model => model.Name)
    <br>
    @Html.Label("By Price Level")
    @Html.DropDownListFor(model => model.PriceLevel, new SelectList(Enum.GetValues(typeof(PriceLevel))), "Select Price Level")
    <br>
    @Html.Label("By Rating")
    @Html.DropDownListFor(model => model.Rating, new SelectList(Enum.GetValues(typeof(Rating))), "Select Rating")
    <br>
    @Html.Label("By Type")
    @Html.DropDownListFor(model => model.Type, new SelectList(@ViewBag.RestaurantType), "Select By Type")
    <br>
    @Html.Label("By Vegetarian")
    @Html.CheckBoxFor(Model => Model.Vegetarian, true) 
    <br>

    <input type="submit" value="Find restaurant" class="btn btn-secondary"/>
  }

<div class="links2">
  <div class="link">
    <p>@Html.ActionLink("Add a new restaurant", "Create")</p>
  </div>
  <div class="link">
    <p>@Html.ActionLink("List of Restaurants", "Index")</p>
  </div>
</div>   

@Html.Partial("Footer")

FavoriteRestaurants/Views/Restaurants/SearchResults.cshtml
@{
  Layout = "_Layout";
  ViewBag.Title = "Search Results for Restaurants";
}

@using FavoriteRestaurants.Models;
@model List<FavoriteRestaurants.Models.Restaurant>;

<div class="jumbotron">
  <h2>Restaurants found by Search</h2>
</div>

 
  @if(@Model.Count == 0)
  {
    <h4>No restaurants matching search found!</h4>
  }

  <table>
    <tr>
      <th>Name</th>
      <th>PriceLevel</th>
      <th>Rating</th>
      <th>Type</th>
      <th>Vegetarian</th>
      <th>Cuisine</th>
    </tr>
 
  @foreach (Restaurant restaurant in Model)
  {
    <tr>
      <td>@Html.ActionLink($"{restaurant.Name} ","Details", new { id = restaurant.RestaurantId })</td>
      <td>@Html.ActionLink($"{restaurant.PriceLevel} ","Details", new { id = restaurant.RestaurantId })</td>
      <td>@Html.ActionLink($"{restaurant.Rating} ","Details", new { id = restaurant.RestaurantId })</td>
      <td>@Html.ActionLink($"{restaurant.Type} ","Details", new { id = restaurant.RestaurantId })</td>
      @if(restaurant.Vegetarian == true)
      {
        <td>@Html.ActionLink("yes","Details", new { id = restaurant.RestaurantId })</td>
      }
      else{
        <td>@Html.ActionLink("no","Details", new { id = restaurant.RestaurantId })</td>
      }
      <td>@Html.ActionLink($"{restaurant.Cuisine.Type} ","Details", new { id = restaurant.RestaurantId })</td>          
    </tr>
  }
</table>


<div class="links3">
  <div class="link">
    <p>@Html.ActionLink("Search for another restaurant", "Search")</p>
  </div>
  <div class="link">
    <p>@Html.ActionLink("Add new restaurant", "Create")</p>
  </div>
  <div class="link">
    <p>@Html.ActionLink("List of restaurants", "Index")</p>
  </div>
</div>

@Html.Partial("Footer")