FavoriteRestaurants/Models/Cuisine.cs
using System.Collections.Generic;

namespace FavoriteRestaurants.Models
{
  public class Cuisine
    {
        public Cuisine()
        {
            this.Restaurants = new HashSet<Restaurant>();
        }

        public int CuisineId { get; set; }
        public string Type { get; set; }
        public virtual ICollection<Restaurant> Restaurants { get; set; }
    }
}

FavoriteRestaurants/Models/Cuisines.cs
using System.Collections.Generic;

namespace FavoriteRestaurants.Models
{
  public class Cuisine
    {
        public Cuisine()
        {
            this.Restaurants = new HashSet<Restaurant>();
        }

        public int CuisineId { get; set; }
        public string Type { get; set; }
        public virtual ICollection<Restaurant> Restaurants { get; set; }
    }
}

FavoriteRestaurants/Controllers/CuisinesController.cs
using Microsoft.AspNetCore.Mvc;
using FavoriteRestaurants.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace FavoriteRestaurants.Controllers
{
  public class CuisinesController : Controller
  {
    private readonly FavoriteRestaurantsContext _db;

    public CuisinesController(FavoriteRestaurantsContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Cuisine> model = _db.Cuisines.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Cuisine cuisine)
    {
      _db.Cuisines.Add(cuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      thisCuisine.Restaurants = _db.Restaurants.Where(x => x.CuisineId == id).ToList();
      _db.SaveChanges();
      return View(thisCuisine);
    }

    public ActionResult Edit(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    [HttpPost]
    public ActionResult Edit(Cuisine cuisine)
    {
      _db.Entry(cuisine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      _db.Cuisines.Remove(thisCuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

FavoriteRestaurants/Controllers/RestaurantsController.cs
using Microsoft.AspNetCore.Mvc;
using FavoriteRestaurants.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FavoriteRestaurants.Controllers
{
  public class RestaurantsController : Controller
  {
    private readonly FavoriteRestaurantsContext _db;

    public RestaurantsController(FavoriteRestaurantsContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Restaurant> model = _db.Restaurants.Include(restaurants => restaurants.Cuisine).ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Type");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Restaurant restaurant)
    {
      _db.Restaurants.Add(restaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      return View(thisRestaurant);
    }

    public ActionResult Edit(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Type");
      return View(thisRestaurant);
    }

    [HttpPost]
    public ActionResult Edit(Restaurant restaurant)
    {
      _db.Entry(restaurant).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      return View(thisRestaurant);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      _db.Restaurants.Remove(thisRestaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    
    public ActionResult Search()
    {
      List<Restaurant> model = _db.Restaurants.Include(restaurants => restaurants.Cuisine).OrderBy(x => x.Type).ToList();
      List<string> modelTypes = new List<string>{};
      foreach (Restaurant restaurant in model)
      {
        modelTypes.Add(restaurant.Type);
      }
      List<string> removedDuplicates = modelTypes.Distinct().ToList();
      ViewBag.RestaurantType = removedDuplicates;
      return View();
    }

    [HttpPost]
    public ActionResult SearchResults(Restaurant searchRestaurant)
    { 
          
      List<Restaurant> allModels = _db.Restaurants.Include(restaurants => restaurants.Cuisine).ToList(); 
      List<Restaurant> foundModels = allModels.ToList();

      if (searchRestaurant.Name != null)
      {
        string nameSearch = searchRestaurant.Name.ToLower();
        foundModels = foundModels.FindAll(x => x.Name.ToLower().Contains(nameSearch) == true);
      }
      if (searchRestaurant.PriceLevel != null)
      {
        foundModels = foundModels.FindAll(x => x.PriceLevel.Contains(searchRestaurant.PriceLevel) == true);
      }
      if (searchRestaurant.Rating != null)
      {
        foundModels = foundModels.FindAll(x => x.Rating.Contains(searchRestaurant.Rating) == true);
      }
      if (searchRestaurant.Type != null)
      {
        foundModels = foundModels.FindAll(x => x.Type.Contains(searchRestaurant.Type) == true);
      }
      if (searchRestaurant.Vegetarian == true)
      {
        foundModels = foundModels.FindAll(x => x.Vegetarian == true);
      }
      return View(foundModels);
    }
  }
}

FavoriteRestaurants/Views/Cuisines/Create.cshtml
@{
  Layout = "_Layout";
  ViewBag.Title = "Add Cuisine";
}

@model FavoriteRestaurants.Models.Cuisine
<div class="jumbotron">
  <h2>Add a new restaurant</h2>
</div>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Type)
    @Html.TextBoxFor(model => model.Type)
    <input type="submit" value="Add new cuisine" class="btn btn-secondary"/>
}
<p>@Html.ActionLink("Show all cuisines", "Index")</p>
@Html.Partial("Footer")

FavoriteRestaurants/Views/Cuisines/Delete.cshtml
@{
  Layout = "_Layout";
  ViewBag.Title = "Delete Cuisine";
}

@model FavoriteRestaurants.Models.Cuisine
<div class="jumbotron">
  <h2>Are you sure you want to delete this?</h2>
</div>

@Html.DisplayNameFor(model => model.Type): @Html.DisplayFor(model => model.Type)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" class="btn btn-secondary"/>
}
@Html.ActionLink("Back to cuisines", "Index")
@Html.Partial("Footer")

FavoriteRestaurants/Views/Cuisines/Details.cshtml
@{
  Layout = "_Layout";
  ViewBag.Title = "Details Cuisine";
}

@using FavoriteRestaurants.Models;
@model FavoriteRestaurants.Models.Cuisine;

<div class="jumbotron">
  <h2>Cuisine Details: @Html.DisplayFor(model => model.Type)</h3></h2>
</div>
<hr />

@if (Model.Type == "French")
{
  <img src="https://cdn.vox-cdn.com/thumbor/0ezcFAbJLt2qYI8Dpz9x9Xpp014=/0x0:3000x2000/1200x675/filters:focal(1232x1367:1712x1847)/cdn.vox-cdn.com/uploads/chorus_image/image/59627533/20160912_Le_Coucou_rabbit_28.0.0.jpg" class="img-fluid">
} 
else if (Model.Type == "Italian")
{
  <img src="https://www.takeaway.com/foodwiki/uploads/sites/11/2019/06/italian-cuisine-47-1440x600.jpg" class="img-fluid">
}
else if (Model.Type == "Chinese")
{
  <img src="https://www.thenational.ae/image/policy:1.884982:1562830908/RM_20190703_DESICHINESE_20.jpg?f=16x9&w=1200&$p$f$w=dfb357e" class="img-fluid">
}
else if (Model.Type == "Mexican")
{
  <img src="https://bigseventravel.com/wp-content/uploads/2019/06/Screenshot-2019-06-23-at-13.06.47.png" class="img-fluid">
}

<div class="content">
  @Html.DisplayFor(model => model.Type) Restaurants:
  <ul>
    @if (@Model.Restaurants.Count == 0)
    {
      <p>no restaurants found</p>
    }

    @foreach (Restaurant restaurant in @Model.Restaurants)
    {
      <li>@Html.ActionLink($"{restaurant.Name}", "Details", "Restaurants", new { id = restaurant.RestaurantId })</li>
    }
  </ul>
</div>



<div class="links4">
  <div class="link">@Html.ActionLink("Back to Cuisines", "Index")</div>
  <div class="link">@Html.ActionLink("Edit Cuisine", "Edit", new { id = Model.CuisineId })</div>
  <div class="link">@Html.ActionLink("Delete Cuisine", "Delete", new { id = Model.CuisineId })</div>
  <div class="link">@Html.ActionLink("Add new Restaurant", "Create", "Restaurants")</div>
</div>
 @Html.Partial("Footer")

FavoriteRestaurants/Views/Cuisines/Edit.cshtml
@{
  Layout = "_Layout";
  ViewBag.Title = "Edit Cuisine";
}

@model FavoriteRestaurants.Models.Cuisine

<div class="jumbotron">
<h2>Edit</h2>
</div>
<h4>Edit @Html.DisplayFor(model => model.Type) cuisine:</h4>
<hr>
<div class="form">
@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.CuisineId)

  @Html.LabelFor(model => model.Type)
  @Html.EditorFor(model => model.Type)
  <br>
  <br>
  <input type="submit" value="Save" class="btn btn-secondary"/>
}
</div>
<br>
<p>@Html.ActionLink("Back to Cuisines", "Index")</p>

@Html.Partial("Footer")

FavoriteRestaurants/Views/Cuisines/Index.cshtml
@{
  Layout = "_Layout";
  ViewBag.Title = "Cuisines";
}

@using FavoriteRestaurants.Models;
@model List<FavoriteRestaurants.Models.Cuisine>;
<div class="jumbotron">
<h1>Cuisines</h1>
</div>

<img src="https://www.foodbusinessnews.net/ext/resources/2019/6/InternationalCuisinesLead1200x800.jpg?1560515989" class="img-fluid" alt="">

<div class="content">
  @if (@Model.Count == 0)
  {
    <h3>No cuisines have been added yet!</h3>
  } 

  @foreach (Cuisine cuisine in Model)
  {
    <li>@Html.ActionLink($"{cuisine.Type}", "Details", new { id = cuisine.CuisineId })</li>
  }
</div>


<div class="link">@Html.ActionLink("Add new Cuisine", "Create")</div>

@Html.Partial("Footer")